#! bin/bash

pomodoro_duration=${1:-25m}

modal() {
  sleep $pomodoro_duration &&
  notify-send "Your turn is over" &&
  zenity \
  --question \
  --text="<span size=\"xx-large\">Your turn is over.</span>\n" \
  --title="Pomotux" \
  --ok-label="again?" 2> /dev/null &&
  if [ $? -eq 0  ]; then modal; fi
}

modal &
